
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-kv
  namespace: axion

spec:
  provider: azure

  secretObjects:
    - secretName: postgres-secret
      type: Opaque
      data:
        - objectName: user-postgres
          key: user-postgres

        - objectName: postgres-password
          key: postgres-password

        - objectName: postgres-db
          key: postgres-db

  parameters:
    usePodIdentity: "false"
    clientID: "8b7a6186-afb5-4aea-b45e-80534f26f22c"

    keyvaultName: "secret02"
    tenantId: "9e93f898-a6b3-40d6-b6fd-690c77a95b13"

    objects: |
      array:
        - |
          objectName: user-postgres
          objectType: secret

        - |
          objectName: postgres-password
          objectType: secret

        - |
          objectName: postgres-db
          objectType: secret